#+title: ESP CTA Bus and Train Tracker
#+author: Aaron Rumph
#+property: header-args :mkdirp yes :comments link :padline yes
#+property: header-args:rust :results silent
#+startup: overview

* Intro

This project is a little side project I worked on this summer. I wanted to make
a little CTA departure board for my girlfriend based on the ones you see at bus
stops and L stops in Chicago. This write-up will explain how I created it,
as well as explain some of the decisions I made for the project! If you are interested in creating your own CTA tracker (or similar transit tracker for other agencies)
you can follow along with this write-up. !!TODO: QUICK GUIDE!!

* Hardware

For this project, I used an esp-32 board from Waveshare with a built-in LCD display. !!TODO: link and hardware info!!

* Tooling

This project was written in Rust using /esp-idf-sys/, which provides Rust bindings
to Espressif's IoT Development Framework (IDF) SDK. I chose Rust for a few reasons:

1. Low-level control:
   Rust is great because it does allow you to write low level code that talks directly to memory. For an embedded project like this, other languages would not necessarily provide the control over memory needed to do MMIO (like for writing to the builtin screen)

2. Reliability:
   With Rust I didn't have to worry about any number of problems that could make my transit tracker unreliable, such as a buffer overflow from CTA's API returning more data than expected.

3. Ecosystem:
   Rust has a number of existing packages (/crates/ in Rust speak) which make this sort of project much easier. For example, /ratatui/ makes it extremely easy to create a TUI on pretty much anything with a display. Additionally, Rust resources for esp-32 
   development are great, with lots of documentation!

4. Familiarity:
   Most importantly, I know Rust and enjoy writing Rust code a lot! Aside from Python, Rust has become the language I use most often, particuarly for side projects, and I wanted to see how far I could take my experience with the language!


* Cargo project configuration

#+begin_src toml :tangle ../Cargo.toml
[package]
name = "esp-cta-tracker"
version = "0.2.0"
authors = ["Aaron Rumph <aaronbrumph@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82" # 1.82 is suggested for working with ESP chips

[[bin]]
harness = false  # do not use the built-in cargo test harness -> resolve rust-analyzer errors
name = "cta-tracker"
path = "src/bin/main.rs"

[dependencies]
# esp-32 and embedded dev crates
embassy-time = { version = "0.5", features = ["generic-queue-8"] }
embedded-graphics = "0.8"
embedded-svc = "0.29.0"
esp-idf-svc = {
  version = "0.52.1",
  features = ["critical-section", "embassy-sync", "embassy-time-driver"]
}

# other crates
anyhow = "1"        # for error handling
heapless = "0.8"    # std::Vec and std::String alternatives with fixed sizes
log = "0.4"         # for quick logging to computer for development

# makes it extremely easy to create a TUI on any display
# all you need to do is write a backend if necessary
# then can use ratatui's existing components to do just about anything
ratatui = {
  version = "0.30",
  default-features = false,
  features = ["all-widgets", "layout-cache", "std"]
}

# super super easy serialization and deserialization
# maybe the single greatest library every made for any language
serde = {
    version = "1", default-features = false, features = ["derive"]
}
serde_json = "1.0"

# bitmap image support for embedded graphics for CTA icons
tinybmp = "0.6.0"

[build-dependencies]
embuild = "0.33"

[profile.dev]
opt-level = "z"
debug = true  # Symbols are nice, and they don't increase the size on Flash

[profile.release]
opt-level = "s"
#+end_src

* Main application

The main application for the transit tracker is just a simple loop. After some setup
when first run, the main loop queries the CTA bus tracker and train tracker APIs to
get arrival times every 30 seconds and then adjusts the TUI display accordingly.


** Initialization and setup

Before the main loop can start, there are a few things we need to setup. First,
we need to import all the modules we will be using. Note that the modules, functions, etc. from /cta_tracker/ are part of the library for this project, not an existing package, and their implementation will be shown later!

#+begin_src rust :tangle ../src/bin/main.rs
use core::ffi::c_void;
use cta_tracker::{
    cta::{CtaPredictions, CtaStop, TransitMode},
    display::{
        color::Rgb565,
        psram::PsramBuffer,
        screen::{Lcd, FRAMEBUFFER_BYTES, LCD_PINS},
    },
};
use embedded_svc::{
    http::client::Client,
    wifi::{AuthMethod, ClientConfiguration, Configuration as WifiConfiguration},
};
use esp_idf_svc::{
    eventloop::EspSystemEventLoop,
    hal::{delay::FreeRtos, peripherals::Peripherals},
    http::client::{Configuration as HttpConfig, EspHttpConnection},
    nvs::EspDefaultNvsPartition,
    sys,
    wifi::{BlockingWifi, EspWifi},
};
use std::time::Duration;

use log::{debug, error, info, warn};
#+end_src

Next, you need to set some useful constants which will be used throughout the main loop.
Because the API requests need Wifi, you need a way of connecting to a network.
You also need API keys for CTA's /Train Tracker/ and /Bus Tracker/ APIs.
I chose to do this by having the Wifi SSID and password read in from a "wifi.env"
file in the project root. I keep my API keys in a "~/.api_keys.env" file.
I chose to read these in at compile time rather than run time to avoid hardcoding
sensitive information into my code. In order to do so, I wrote a 'build.rs' file:

#+begin_src rust :tangle ../build.rs
use std::{env, fs, path::PathBuf};

fn main() {
    embuild::espidf::sysenv::output();

    // This function loads the 'wifi.env' file in the project root
    load_project_wifi_env();
    // This function loads my API keys from ~/.api_keys.env
    load_home_api_keys_env();
}

/// Loads 'WIFI_SSID' and 'WIFI_PASSWORD' env variables from 'wifi.env'
/// file in the project root directory.
fn load_project_wifi_env() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let wifi_env = manifest_dir.join("wifi.env");

    println!("cargo:rerun-if-changed={}", wifi_env.display());

    load_env_file(&wifi_env, &["WIFI_SSID", "WIFI_PASSWORD"]);
}

/// Loads 'CTA_BUS_API_KEY' and 'CTA_TRAIN_API_KEY' env variables from
/// '~/.api_keys.env'.
fn load_home_api_keys_env() {
    /* NOTE: I choose to keep my API keys in ~/.api_keys.env.
    If you keep them somewhere else you should adjust the
    following code to look in the correct paths */
    let home = env::var("HOME").expect("HOME is not set");
    let api_env = PathBuf::from(home).join(".api_keys.env");

    println!("cargo:rerun-if-changed={}", api_env.display());
    println!("cargo:rerun-if-env-changed=HOME");

    load_env_file(&api_env, &["CTA_BUS_API_KEY", "CTA_TRAIN_API_KEY"]);
}

/// Simple parser for **.env** files that loads any variables
/// into rustc-env variables.
fn load_env_file(path: &PathBuf, allowed_keys: &[&str]) {
    let contents = fs::read_to_string(path).unwrap_or_else(|e| panic!("Couldn't read {}: {e}", path.display()));

    for line in contents.lines() {
        let line = line.trim();

        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let Some((key, value)) = line.split_once('=') else {
            panic!("invalid line in {}: {line}", path.display());
        };

        let key = key.trim();
        let value = value.trim().trim_matches('"').trim_matches('\'');

        if allowed_keys.contains(&key) {
            println!("cargo:rustc-env={key}={value}");
        }
    }
}
#+end_src

!!TODO: rest of library!! 
!!TODO: figure out many-to-many tangle?!!
